### ISSUE TITLE
issue to get coordinates of all bodyparts of dlc prediction 

### ISSUE THREAD

**Issue by josefinemeyer** [ulisesrey/imutils#11]
imutils code in get_absolute_bodyparts_coords.sh of epifluorescence_calcium_imaging pipeline is limited to one body part. see line: 

https://github.com/ulisesrey/imutils/blob/9258cdc911ceec0b68a54e61c76d2ae7f3e8281e/imutils/src/bodyparts_coordinates.py#L47

thank you

**Comment by ulisesrey** [comment]
should be fixed, now. Can you check @josefinemeyer ?
make sure that you have the latest version of the file
epifluorescence_calcium_imaging/bash_scripts/get_absolute_bodyparts_coords.sh

**Comment by josefinemeyer** [comment]
I added the config.yaml and got this error

could you please check that out, @ulisesrey ?

All jobs in this array have:
- SLURM_ARRAY_JOB_ID=7622447
- SLURM_ARRAY_TASK_COUNT=5
- SLURM_ARRAY_TASK_MIN=1
- SLURM_ARRAY_TASK_MAX=5
This job in the array has:
- SLURM_JOB_ID=7622450
- SLURM_ARRAY_TASK_ID=1
My PROJECT iS /scratch/neurobiology/zimmer/active_sensing/zim06/zim2391/recordings_zim2391_RIA/20230516/data/worm3
My config.yaml filepath is /scratch/neurobiology/zimmer/active_sensing/zim06/zim2391/recordings_zim2391_RIA/20230516/data/worm3/config.yaml
Environment loaded?
Entering Python code..
The recording has 440 520 as center of coordiantes
usage: bodyparts_coordinates.py [-h] -p PROJECT_PATH -img_center_coords
                                IMAGE_CENTER_COORDINATES
                                [IMAGE_CENTER_COORDINATES ...] -px_dim
                                PIXEL_DIMENSIONS
bodyparts_coordinates.py: error: argument -img_center_coords/--image_center_coordinates: invalid float value: '{BEH_CENTER_X}'
usage: bodyparts_coordinates.py [-h] -p PROJECT_PATH -img_center_coords
                                IMAGE_CENTER_COORDINATES
                                [IMAGE_CENTER_COORDINATES ...] -px_dim
                                PIXEL_DIMENSIONS
bodyparts_coordinates.py: _**error: argument -img_center_coords/--image_center_coordinates: invalid float value: '{BEH_CENTER_X}'**_
usage: bodyparts_coordinates.py [-h] -p PROJECT_PATH -img_center_coords
                                IMAGE_CENTER_COORDINATES
                                [IMAGE_CENTER_COORDINATES ...] -px_dim
                                PIXEL_DIMENSIONS
bodyparts_coordinates.py: error: argument -img_center_coords/--image_center_coordinates: invalid float value: '{BEH_CENTER_X}'
FINISHED
find: missing argument to `-exec'

**Comment by ulisesrey** [comment]
It works now after changing this:
https://github.com/ulisesrey/epifluorescence_calcium_imaging/commit/34c24be6e30bcc8a431ba9435175cb5280540f7f

Important, the nose is annotated in DLC as head, so the file is named head_coords_mm.csv now.
